### ISSUE TITLE
Wiki for Github

### ISSUE THREAD

**Issue by jannesgg** [ocean-data-factory-sweden/kso-data-management#36]
- [ ] Tutorial 1
- [ ] Tutorial 2
- [ ] Tutorial 3
- [ ] Tutorial 4
- [ ] Tutorial 5
- [ ] Tutorial 6
- [ ] Tutorial 7
- [ ] Tutorial 8
- [ ] Tutorial 9
- [ ] Tutorial 10

It would be useful to combine the insights of @Bergylta and @Diewertje11 to guide users on common issues for each notebook.

**Comment by jannesgg** [comment]
@Bergylta Any updates on this?

**Comment by Bergylta** [comment]
@jannesgg been slowly working my way through, haven't had much time for it though. Will update as soon as i possibly can.
