### ISSUE TITLE
Issue in tutorial 3

### ISSUE THREAD

**Issue by Bergylta** [ocean-data-factory-sweden/kso-data-management#54]
ValueError                                Traceback (most recent call last)
File /usr/local/lib/python3.8/site-packages/dataclass_csv/dataclass_reader.py:232, in DataclassReader._process_row(self, row)
    231 try:
--> 232     transformed_value = field_type(value)
    233 except ValueError as e:

ValueError: invalid literal for int() with base 10: 'None'

The above exception was the direct cause of the following exception:

CsvValueError                             Traceback (most recent call last)
Cell In [6], line 3
      1 # @title <font size="5">↓ ឵឵<i>Initiate project's database</font> { vertical-output: true }
      2 # Save the name of the project
----> 3 project = p_utils.find_project(project_name=project_name.value)
      5 # Initiate db
      6 db_info_dict = t_utils.initiate_db(project)

File /usr/src/app/koster_data_management/kso_utils/project_utils.py:53, in find_project(project_name)
     51 with open(project_path) as csv:
     52     reader = DataclassReader(csv, Project)
---> 53     for row in reader:
     54         if row.Project_name == project_name:
     55             logging.info(f"{project_name} loaded succesfully")

File /usr/local/lib/python3.8/site-packages/dataclass_csv/dataclass_reader.py:247, in DataclassReader.__next__(self)
    245 def __next__(self):
    246     row = next(self._reader)
--> 247     return self._process_row(row)

File /usr/local/lib/python3.8/site-packages/dataclass_csv/dataclass_reader.py:234, in DataclassReader._process_row(self, row)
    232     transformed_value = field_type(value)
    233 except ValueError as e:
--> 234     raise CsvValueError(
    235         (
    236             f"The field `{field.name}` is defined as {field.type} "
    237             f"but received a value of type {type(value)}."
    238         ),
    239         line_number=self._reader.line_num,
    240     ) from e
    241 else:
    242     values[field.name] = transformed_value

CsvValueError: The field `Zooniverse_number` is defined as <class 'int'> but received a value of type <class 'str'>. [CSV Line number: 6]

**Comment by jannesgg** [comment]
@Bergylta Can you try to take move the updated scripts from /mimer/NOBACKUP/snic2022-22-1210/jupyter_envs into your home directory and then try to start another session and test again? I just need to confirm that we are using the same version of the repository.

**Comment by jannesgg** [comment]
@Bergylta Is this working as expected now?
