### ISSUE TITLE
Tutorial 4 issue with retrieving the frames

### ISSUE THREAD

**Issue by Bergylta** [ocean-data-factory-sweden/kso-data-management#59]
INFO:root:737 Zooniverse classifications have been retrieved
INFO:root:Aggregrating the classifications
INFO:root:Updated agg_annotations_clip
0 classifications aggregated out of 620 unique subjects available
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File /usr/local/lib/python3.8/dist-packages/ipyfilechooser/filechooser.py:268, in FileChooser._on_select_click(self, _b)
    266 if self._callback is not None:
    267     try:
--> 268         self._callback(self)
    269     except TypeError:
    270         # Support previous behaviour of not passing self
    271         self._callback()

File /usr/src/app/koster_data_management/kso_utils/t4_utils.py:484, in get_frames.<locals>.extract_files(chooser)
    481 populate_agg_annotations(sp_agg_clips_df, "clip", project)
    483 # Get df of frames to be extracted
--> 484 frame_df = get_species_frames(
    485     sp_agg_clips_df,
    486     species_ids,
    487     server_dict,
    488     conn,
    489     project,
    490     n_frames_subject,
    491 )
    493 # Check the frames haven't been uploaded to Zooniverse
    494 frame_df = check_frames_uploaded(frame_df, project, species_ids, conn)

File /usr/src/app/koster_data_management/kso_utils/t4_utils.py:211, in get_species_frames(agg_clips_df, species_ids, server_dict, conn, project, n_frames_subject)
    209 # Identify the ordinal number of the frames expected to be extracted
    210 if len(frames_df) == 0:
--> 211     raise ValueError("No frames. Workflow stopped.")
    213 frames_df["frame_number"] = frames_df[["first_seen_movie", "fps"]].apply(
    214     lambda x: [
    215         int((x["first_seen_movie"] + j) * x["fps"]) for j in range(n_frames_subject)
    216     ],
    217     1,
    218 )
    220 # Reshape df to have each frame as rows

ValueError: No frames. Workflow stopped.

**Comment by jannesgg** [comment]
@Bergylta Have you tested whether lowering the aggregation criteria changes anything?

**Comment by Bergylta** [comment]
I have checked with aggregation thresholds of 0,1 and min user 1, still the same
@jannesgg

**Comment by jannesgg** [comment]
@Bergylta Please also provide other parameters such as the project name, workflow ids etc so I can try to reproduce the issue.

**Comment by Bergylta** [comment]
@jannesgg 
Project is GU
species choice is: European green crab, Black goby, Round goby and Goby (Any species) <- tried them one by one
1 workflow: Fish ID, Subject type: Clips, Minimum workflow version: 1.0

Agg threshold 0.2
Min no Users: 1

**Comment by jannesgg** [comment]
@Bergylta Please delete this folder /mimer/NOBACKUP/groups/snic2022-22-1210/tmp_dir/Frames/ when you can. And in future, when you have to create a new folder, you can write the name of the folder inside the widget (in the open field next to the one that contains the path you searched for). This will create the folder and all others required below it and give them the correct permissions. Otherwise we run into the issue again that only certain people can remove files / folders, which is not necessary for tmp_dir as we need to be able to clear this at any time.

**Comment by Bergylta** [comment]
thank you @jannesgg it is working now :)
