### ISSUE TITLE
Issue with modifications of frames in tutorial 4

### ISSUE THREAD

**Issue by Bergylta** [ocean-data-factory-sweden/kso-data-management#60]
Number of modifications: 1
Select modification : Zoo_low_compression
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In[16], line 2
      1 # Modify the clips
----> 2 frames_ready_df = t4.modify_frames(
      3     frames_to_upload_df=frames_to_upload_df.df.reset_index(drop=True),
      4     species_i=species_i.value,
      5     modification_details=frame_modification.checks,
      6     project=project,
      7 )

File /usr/src/app/koster_data_management/kso_utils/t4_utils.py:673, in modify_frames(frames_to_upload_df, species_i, modification_details, project)
    671 # Create the folder to store the videos if not exist
    672 if not os.path.exists(mod_frames_folder):
--> 673     os.mkdir(mod_frames_folder)
    674     os.chmod(mod_frames_folder, 0o777)
    676 #### Modify the clips###
    677 # Read each clip and modify them (printing a progress bar)

PermissionError: [Errno 13] Permission denied: '/mimer/NOBACKUP/groups/snic2022-22-1210/tmp_dir/frames/modified_European green crab_frames/'

**Comment by jannesgg** [comment]
@Bergylta Another permissions issue. Should be fixed by latest changes.

**Comment by Bergylta** [comment]
@jannesgg Well, the permission issue seems to be gone, but now there is a different error in the same place
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[14], line 2
      1 # Modify the clips
----> 2 frames_ready_df = t4.modify_frames(
      3     frames_to_upload_df=frames_to_upload_df.df.reset_index(drop=True),
      4     species_i=species_i.value,
      5     modification_details=frame_modification.checks,
      6     project=project,
      7 )

File /usr/src/app/koster_data_management/kso_utils/t4_utils.py:673, in modify_frames(frames_to_upload_df, species_i, modification_details, project)
    671 # Create the folder to store the videos if not exist
    672 if not os.path.exists(mod_frames_folder):
--> 673     os.mkdir(mod_frames_folder)
    674     os.chmod(mod_frames_folder, 0o777)
    676 #### Modify the clips###
    677 # Read each clip and modify them (printing a progress bar)

FileNotFoundError: [Errno 2] No such file or directory: '/mimer/NOBACKUP/groups/snic2022-22-1210/tmp_dir/frames/modified_Goby (any species)_frames/'

**Comment by jannesgg** [comment]
@Bergylta Updated. Please test again.

**Comment by Bergylta** [comment]
thank you @jannesgg 
it is working as it should now :D
