### ISSUE TITLE
Users of the template project need to be collaborators of the zooniverse, or we should build up the notebooks differently

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso-data-management#62]
When you are not an collaborator of the zooniverse of the template project, you cannot access the videos. The problem here is in the .get_export() and is described on this forum: 
['Generate' option in Project export raises project id not found error · Issue #171 · zooniverse/panoptes-python-client (github.com)](https://github.com/zooniverse/panoptes-python-client/issues/171)
It also describes that you can make the exports available via an HTML link instead, which would be a work around. However, we need to check with the rest of the notebook(s) if there are not more functionalities that are not possible without being a collaborator. If so, maybe we should make it possible that everyone becomes one. Or set up the notebooks differently.

**Comment by victor-wildlife** [comment]
@Diewertje11 I think making the exports available via HTML will be good for tut#8 as we only interact with Zooniverse to retrieve the information. For tut#3 and #4 users will need to be part of a Zoo project. Where did you read how to make the exports available via HTML?

**Comment by Diewertje11** [comment]
@victor-wildlife, That is good to know! I did already implement it for tut#8, I only did not merge my branch yet. But how I have done it now is that I manually downloaded the files from Zooniverse and uploaded them to a google drive. In the code (Zooniverse_utils.retrieve_zoo_info) I added that if the Zooniverse account info is 'None', that it should download it from the drive. If you go into my branch: tut_4_8_updates, you can see it.

Do you think that this way of doing it is sufficient? Or do you have another proposal?

(I hope to finish up my updates today and make a merge request)
